In [2]:
import pandas as pd

movies = pd.read_csv("../data/raw/movielens/movies.csv")
ratings = pd.read_csv("../data/raw/movielens/ratings.csv")
tags = pd.read_csv("../data/raw/movielens/tags.csv")
links = pd.read_csv("../data/raw/movielens/links.csv")

In [3]:
print("Movies:", movies.shape)
print("Ratings:", ratings.shape)
print("Tags:", tags.shape)
print("Links:", links.shape)

Movies: (87585, 3)
Ratings: (32000204, 4)
Tags: (2000072, 4)
Links: (87585, 3)

In [4]:
movies.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [5]:
ratings.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [6]:
tags.isnull().sum()

userId        0
movieId       0
tag          17
timestamp     0
dtype: int64

In [7]:
links.isnull().sum()

movieId      0
imdbId       0
tmdbId     124
dtype: int64

In [8]:

movies.duplicated().sum()

np.int64(0)

In [9]:
ratings.duplicated().sum()

np.int64(0)

In [10]:
tags.duplicated().sum()

np.int64(0)

In [11]:
links.duplicated().sum()

np.int64(0)

In [12]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87585 entries, 0 to 87584
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  87585 non-null  int64
 1   title    87585 non-null  object
 2   genres   87585 non-null  object
dtypes: int64(1), object(2)
memory usage: 2.0+ MB

In [13]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32000204 entries, 0 to 32000203
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 976.6 MB

In [14]:
tags.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000072 entries, 0 to 2000071
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   tag        object
 3   timestamp  int64
dtypes: int64(3), object(1)
memory usage: 61.0+ MB

In [15]:
links.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87585 entries, 0 to 87584
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  87585 non-null  int64
 1   imdbId   87585 non-null  int64
 2   tmdbId   87461 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 2.0 MB

In [16]:
ratings["rating"].describe()

count    3.200020e+07
mean     3.540396e+00
std      1.058986e+00
min      5.000000e-01
25%      3.000000e+00
50%      3.500000e+00
75%      4.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

In [17]:
ratings["userId"].nunique()

200948

In [18]:
tags["tag"].nunique()

140979

In [19]:
links.head(10)

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0
5        6  113277    949.0
6        7  114319  11860.0
7        8  112302  45325.0
8        9  114576   9091.0
9       10  113189    710.0

In [20]:
# Average Rating per Movie

movie_ratings = ratings.groupby("movieId").agg(
    avg_rating=("rating", "mean"),
    rating_count=("rating", "count")
).reset_index()

movie_ratings.head()

   movieId  avg_rating  rating_count
0        1    3.897438         68997
1        2    3.275758         28904
2        3    3.139447         13134
3        4    2.845331          2806
4        5    3.059602         13154

In [21]:
# Number of Tags per Movie

movie_tags = tags.groupby("movieId").agg(
    tag_count=("tag", "count")
).reset_index()

movie_tags.head()

   movieId  tag_count
0        1       1230
1        2        573
2        3         23
3        4         12
4        5         64

In [22]:
# Merge Data

master_df = movies.merge(movie_ratings,on="movieId",how="left")
master_df = master_df.merge(movie_tags,on="movieId",how="left")
master_df = master_df.merge(links,on="movieId",how="left")

master_df.head()

,movieId,title,genres,avg_rating,rating_count,tag_count,imdbId,tmdbId
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.897438,68997.0,1230.0,114709,862.0
1,2,Jumanji (1995),Adventure|Children|Fantasy,3.275758,28904.0,573.0,113497,8844.0
2,3,Grumpier Old Men (1995),Comedy|Romance,3.139447,13134.0,23.0,113228,15602.0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,2.845331,2806.0,12.0,114885,31357.0
4,5,Father of the Bride Part II (1995),Comedy,3.059602,13154.0,64.0,113041,11862.0

In [23]:
master_df.shape

(87585, 8)

In [24]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87585 entries, 0 to 87584
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movieId       87585 non-null  int64
 1   title         87585 non-null  object
 2   genres        87585 non-null  object
 3   avg_rating    84432 non-null  float64
 4   rating_count  84432 non-null  float64
 5   tag_count     51323 non-null  float64
 6   imdbId        87585 non-null  int64
 7   tmdbId        87461 non-null  float64
dtypes: float64(4), int64(2), object(2)
memory usage: 5.3+ MB

In [25]:
master_df.isnull().sum()

movieId             0
title               0
genres              0
avg_rating       3153
rating_count     3153
tag_count       36262
imdbId              0
tmdbId            124
dtype: int64